/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import org.example.Engine;
import org.example.Document;
import java.util.Scanner;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.FileInputStream;


public class App {

    public static void openDocument(Document document, Scanner sc, int width) {
        boolean NewDoc = true;
                while(NewDoc) {
                        System.out.print("COMMANDS[add, print, exit, save]: ");
                        String command2 = sc.nextLine();
                        switch(command2) {
                        case "add":
                            System.out.print("Enter line(must be less than " + width + " characters): ");
                            String line = sc.nextLine();
                            System.out.print("Enter formatting[left, right, center]: ");
                            String formatting = sc.nextLine();
                            document.addLine(line, formatting);
                            break;
                        case "print":
                            Engine.printDocument(document);
                            break;
                        case "exit":
                            NewDoc = false;
                            break;
                        case "save":
                            System.out.print("Enter file name to save: ");
                            String fileName = sc.nextLine();
                            try (FileOutputStream fileOut = new FileOutputStream(fileName + ".javaDoc");
                                ObjectOutputStream out = new ObjectOutputStream(fileOut)) {
                                    out.writeObject(document);
                                    System.out.println("Document Serialized to: " + fileName + ".javaDoc");
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                            break;
                    }
                }
    }
    public static void main(String[] args) {
        boolean running = true;
        Scanner sc = new Scanner(System.in);
        while(running) {
            System.out.print("COMMANDS[new, exit, open]: ");
            String command = sc.nextLine();
            switch(command) {
                case "new":
                    Document document = new Document();
                    int height = 0;
                    int width = 0;
                    System.out.print("Enter document width: ");
                    width = sc.nextInt();
                    System.out.print("Enter document height: ");
                    height = sc.nextInt();
                    document.ImportDocument(new ArrayList<String>(), new ArrayList<String>(), width, height);
                    sc.nextLine();
                    openDocument(document, sc, width);

                    break;

                case "open":
                    System.out.print("Enter name of file: ");
                    String name = sc.nextLine();


                    try (FileInputStream fileIn = new FileInputStream(name);
                    ObjectInputStream in = new ObjectInputStream(fileIn)) {
                        document = (Document) in.readObject();
                        width = document.width;
                        openDocument(document, sc, width);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    break;
                case "exit":
                    running = false;
                    break;
            }
        }
    }
}
