/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import org.example.Engine;
import org.example.Document;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        boolean running = true;
        Scanner sc = new Scanner(System.in);
        while(running) {
            System.out.print("COMMANDS[new, exit]: ");
            String command = sc.nextLine();
            switch(command) {
                case "new":
                    
                    boolean NewDoc = true;
                    Document document = new Document();
                    int height = 0;
                    int with = 0;
                    System.out.print("Enter document width: ");
                    with = sc.nextInt();
                    System.out.print("Enter document height: ");
                    height = sc.nextInt();
                    document.ImportDocument(new ArrayList<String>(), new ArrayList<String>(), with, height);
                    sc.nextLine();
                    while(NewDoc) {
                        System.out.print("COMMANDS[add, print, exit]: ");
                        String command2 = sc.nextLine();
                        switch(command2) {
                            case "add":
                                System.out.print("Enter line(must be less than " + with + " characters): ");
                                String line = sc.nextLine();
                                System.out.print("Enter formatting[left, right, center]: ");
                                String formatting = sc.nextLine();
                                document.addLine(line, formatting);
                                break;
                            case "print":
                                Engine.printDocument(document);
                                break;
                            case "exit":
                                NewDoc = false;
                                break;
                        }
                    }
                    break;
                case "exit":
                    running = false;
                    break;
            }
        }
    }
}
