/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import org.example.Engine;
import org.example.Document;

public class App {

    public static void main(String[] args) {
        Document document = new Document();
        document.ImportDocument(new ArrayList<String>(), new ArrayList<String>(), 32, 90);
        document.addLine("Heath Document No. 1", "left");
        document.addLine("This is a test document.\nthis is a test of Engine.java", "right");
        document.addLine("END of document", "left");
        Engine.printDocument(document);
    }
}
