/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import org.example.Engine;
import org.example.Document;
import java.util.Scanner;

public class AppTower {

    public static void main(String[] args) {
        Document document = new Document();
        document.ImportDocument(new ArrayList<String>(), new ArrayList<String>(), 32, 15);
        document.addLine("this line is too long to fit in the document", "left");
        document.addLine("fancy fox  1 2 3 OwO im a furry", "left");
        Engine.printDocument(document);
    }
}

